#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libmodbus
Version  : 3.1.4
Release  : 2
URL      : https://libmodbus.org/releases/libmodbus-3.1.4.tar.gz
Source0  : https://libmodbus.org/releases/libmodbus-3.1.4.tar.gz
Summary  : Modbus library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libmodbus-lib = %{version}-%{release}
Requires: libmodbus-license = %{version}-%{release}
Requires: libmodbus-man = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : xmlto

%description
A groovy modbus library
=======================
[![Build Status](https://travis-ci.org/stephane/libmodbus.svg?branch=master)](https://travis-ci.org/stephane/libmodbus)

%package dev
Summary: dev components for the libmodbus package.
Group: Development
Requires: libmodbus-lib = %{version}-%{release}
Provides: libmodbus-devel = %{version}-%{release}

%description dev
dev components for the libmodbus package.


%package doc
Summary: doc components for the libmodbus package.
Group: Documentation
Requires: libmodbus-man = %{version}-%{release}

%description doc
doc components for the libmodbus package.


%package lib
Summary: lib components for the libmodbus package.
Group: Libraries
Requires: libmodbus-license = %{version}-%{release}

%description lib
lib components for the libmodbus package.


%package license
Summary: license components for the libmodbus package.
Group: Default

%description license
license components for the libmodbus package.


%package man
Summary: man components for the libmodbus package.
Group: Default

%description man
man components for the libmodbus package.


%prep
%setup -q -n libmodbus-3.1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543217322
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1543217322
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libmodbus
cp COPYING.LESSER %{buildroot}/usr/share/package-licenses/libmodbus/COPYING.LESSER
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/modbus/modbus-rtu.h
/usr/include/modbus/modbus-tcp.h
/usr/include/modbus/modbus-version.h
/usr/include/modbus/modbus.h
/usr/lib64/libmodbus.so
/usr/lib64/pkgconfig/libmodbus.pc
/usr/share/man/man3/modbus_close.3
/usr/share/man/man3/modbus_connect.3
/usr/share/man/man3/modbus_flush.3
/usr/share/man/man3/modbus_free.3
/usr/share/man/man3/modbus_get_byte_from_bits.3
/usr/share/man/man3/modbus_get_byte_timeout.3
/usr/share/man/man3/modbus_get_float.3
/usr/share/man/man3/modbus_get_float_abcd.3
/usr/share/man/man3/modbus_get_float_badc.3
/usr/share/man/man3/modbus_get_float_cdab.3
/usr/share/man/man3/modbus_get_float_dcba.3
/usr/share/man/man3/modbus_get_header_length.3
/usr/share/man/man3/modbus_get_response_timeout.3
/usr/share/man/man3/modbus_get_socket.3
/usr/share/man/man3/modbus_mapping_free.3
/usr/share/man/man3/modbus_mapping_new.3
/usr/share/man/man3/modbus_mapping_new_start_address.3
/usr/share/man/man3/modbus_mask_write_register.3
/usr/share/man/man3/modbus_new_rtu.3
/usr/share/man/man3/modbus_new_tcp.3
/usr/share/man/man3/modbus_new_tcp_pi.3
/usr/share/man/man3/modbus_read_bits.3
/usr/share/man/man3/modbus_read_input_bits.3
/usr/share/man/man3/modbus_read_input_registers.3
/usr/share/man/man3/modbus_read_registers.3
/usr/share/man/man3/modbus_receive.3
/usr/share/man/man3/modbus_receive_confirmation.3
/usr/share/man/man3/modbus_reply.3
/usr/share/man/man3/modbus_reply_exception.3
/usr/share/man/man3/modbus_report_slave_id.3
/usr/share/man/man3/modbus_rtu_get_rts.3
/usr/share/man/man3/modbus_rtu_get_rts_delay.3
/usr/share/man/man3/modbus_rtu_get_serial_mode.3
/usr/share/man/man3/modbus_rtu_set_custom_rts.3
/usr/share/man/man3/modbus_rtu_set_rts.3
/usr/share/man/man3/modbus_rtu_set_rts_delay.3
/usr/share/man/man3/modbus_rtu_set_serial_mode.3
/usr/share/man/man3/modbus_send_raw_request.3
/usr/share/man/man3/modbus_set_bits_from_byte.3
/usr/share/man/man3/modbus_set_bits_from_bytes.3
/usr/share/man/man3/modbus_set_byte_timeout.3
/usr/share/man/man3/modbus_set_debug.3
/usr/share/man/man3/modbus_set_error_recovery.3
/usr/share/man/man3/modbus_set_float.3
/usr/share/man/man3/modbus_set_float_abcd.3
/usr/share/man/man3/modbus_set_float_badc.3
/usr/share/man/man3/modbus_set_float_cdab.3
/usr/share/man/man3/modbus_set_float_dcba.3
/usr/share/man/man3/modbus_set_response_timeout.3
/usr/share/man/man3/modbus_set_slave.3
/usr/share/man/man3/modbus_set_socket.3
/usr/share/man/man3/modbus_strerror.3
/usr/share/man/man3/modbus_tcp_accept.3
/usr/share/man/man3/modbus_tcp_listen.3
/usr/share/man/man3/modbus_tcp_pi_accept.3
/usr/share/man/man3/modbus_tcp_pi_listen.3
/usr/share/man/man3/modbus_write_and_read_registers.3
/usr/share/man/man3/modbus_write_bit.3
/usr/share/man/man3/modbus_write_bits.3
/usr/share/man/man3/modbus_write_register.3
/usr/share/man/man3/modbus_write_registers.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libmodbus/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmodbus.so.5
/usr/lib64/libmodbus.so.5.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libmodbus/COPYING.LESSER

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/libmodbus.7
