#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libmodbus
Version  : 3.1.10
Release  : 7
URL      : https://github.com/stephane/libmodbus/releases/download/v3.1.10/libmodbus-3.1.10.tar.gz
Source0  : https://github.com/stephane/libmodbus/releases/download/v3.1.10/libmodbus-3.1.10.tar.gz
Summary  : Modbus library
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.1
Requires: libmodbus-lib = %{version}-%{release}
Requires: libmodbus-license = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# A groovy modbus library
![Build Status](https://github.com/stephane/libmodbus/actions/workflows/build.yml/badge.svg)

%package dev
Summary: dev components for the libmodbus package.
Group: Development
Requires: libmodbus-lib = %{version}-%{release}
Provides: libmodbus-devel = %{version}-%{release}
Requires: libmodbus = %{version}-%{release}

%description dev
dev components for the libmodbus package.


%package doc
Summary: doc components for the libmodbus package.
Group: Documentation

%description doc
doc components for the libmodbus package.


%package lib
Summary: lib components for the libmodbus package.
Group: Libraries
Requires: libmodbus-license = %{version}-%{release}

%description lib
lib components for the libmodbus package.


%package license
Summary: license components for the libmodbus package.
Group: Default

%description license
license components for the libmodbus package.


%prep
%setup -q -n libmodbus-3.1.10
cd %{_builddir}/libmodbus-3.1.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1674261461
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1674261461
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libmodbus
cp %{_builddir}/libmodbus-%{version}/COPYING.LESSER %{buildroot}/usr/share/package-licenses/libmodbus/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/libmodbus-%{version}/tests/LICENSE %{buildroot}/usr/share/package-licenses/libmodbus/7430e083dee545c9b903ed98eb888f9b85af4d9b || :
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/modbus/modbus-rtu.h
/usr/include/modbus/modbus-tcp.h
/usr/include/modbus/modbus-version.h
/usr/include/modbus/modbus.h
/usr/lib64/libmodbus.so
/usr/lib64/pkgconfig/libmodbus.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libmodbus/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmodbus.so.5
/usr/lib64/libmodbus.so.5.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libmodbus/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/libmodbus/7430e083dee545c9b903ed98eb888f9b85af4d9b
